name: Build Multi-Architecture ROS Containers

on:
  push:
    tags:
      - 'dev*'
      - 'latest'
      - 'v*'

jobs:
  
  # Detect file changes and set conditions for subsequent jobs
  check-conditions:
    runs-on: ubuntu-latest
    
    outputs:
      ros2-amd64: ${{ steps.filter.outputs.ros2-amd64 }}
      ros2-jetson: ${{ steps.filter.outputs.ros2-jetson }}
      workflow: ${{ steps.filter.outputs.workflow }}
      image_version: ${{ steps.set_version.outputs.image_version }}
    
      permissions:
      packages: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history to compare with previous commits

      - name: Check the branch
        id: branch-check
        run: |
          # find all remote branches containing this commit
          branches=$(git branch -r --contains $GITHUB_SHA)
          echo "::set-output name=branches::$branches"

      - name: Fail if tag is invalid
        if: |
          startsWith(github.ref, 'refs/tags/dev') ||
          ( (github.ref == 'refs/tags/latest' || startsWith(github.ref, 'refs/tags/v')) &&
            contains( steps.branch-check.outputs.branches, 'origin/master' ) )
        run: |
          echo "Tag $GITHUB_REF is not on master. Aborting."
          exit 1
      
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ros2-amd64:
              - 'ROS2/AMD64x86/**'
            workflow:
              - '.github/workflows/**'
#           ros2-jetson:
#             - 'ROS2/Jetson/**'

      - name: Set image version
        id: set_version
        run: |
          echo "image_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  # Stage 1: ROS2 base humble images (AMD64/x86)
  ros2-humble-base-amd64:
    needs: check-conditions
    if: ${{ needs.check-conditions.outputs.ros2-amd64 == 'true' || needs.check-conditions.outputs.workflow == 'true' }}
    name: ROS2 Humble Base Images (AMD64)
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/AMD64x86/humble', image_name: 'humble', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
          - { build_context: './ROS2/AMD64x86/humble_gpu', image_name: 'humble_gpu', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-latest

  # Stage 1: ROS2 base humble images (Jetson/ARM)
  # ros2-humble-jetson:
  #   needs: check-conditions
  #   if: ${{ needs.check-conditions.outputs.ros2-jetson == 'true' || needs.check-conditions.outputs.workflow == 'true' }}
  #   name: ROS2 Humble Jetson Base
  #   permissions:
  #     packages: write
  #     contents: read
  #   strategy:
  #     matrix:
  #       config:
  #         - { build_context: './ROS2/Jetson/humble_jetson', image_name: 'humble_jetson', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
  #   uses: ./.github/workflows/build-workflow.yaml
  #   with:
  #     build_context: ${{ matrix.config.build_context }}
  #     image_name: ${{ matrix.config.image_name }}
  #     image_version: ${{ matrix.config.image_version }}
  #     runs_on: ubuntu-24.04-arm

  # Stage 2: ROS2 humble_harmonic (depends on base humble)
  ros2-humble-harmonic:
    needs: [check-conditions, ros2-humble-base-amd64]
    if: ${{ needs.check-conditions.outputs.ros2-amd64 == 'true' || needs.check-conditions.outputs.workflow == 'true' }}
    name: ROS2 Humble Harmonic
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/AMD64x86/humble_harmonic', image_name: 'humble_harmonic', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-latest

  # Stage 3: ROS2 wheelchair2_base images (AMD64/x86)
  ros2-wheelchair-base:
    needs: [check-conditions, ros2-humble-base-amd64, ros2-humble-harmonic]
    if: ${{ needs.check-conditions.outputs.ros2-amd64 == 'true' || needs.check-conditions.outputs.workflow == 'true' }}
    name: ROS2 Wheelchair2 Base Images
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/AMD64x86/wheelchair2_base', image_name: 'wheelchair2_base', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
          - { build_context: './ROS2/AMD64x86/wheelchair2_base_gazebo', image_name: 'wheelchair2_base_gazebo', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-latest

  # Stage 3: ROS2 wheelchair2_base_jetson (depends on humble_jetson)
  # ros2-wheelchair-jetson:
  #   needs: [check-conditions, ros2-humble-jetson]
  #   if: ${{ needs.check-conditions.outputs.ros2-jetson == 'true' || needs.check-conditions.outputs.workflow == 'true' }}
  #   name: ROS2 Wheelchair2 Jetson Images
  #   permissions:
  #     packages: write
  #     contents: read
  #   strategy:
  #     matrix:
  #       config:
  #         - { build_context: './ROS2/Jetson/wheelchair2_base_jetson', image_name: 'wheelchair2_base_jetson', image_version: "${{ needs.check-conditions.outputs.image_version }}" }
  #   uses: ./.github/workflows/build-workflow.yaml
  #   with:
  #     build_context: ${{ matrix.config.build_context }}
  #     image_name: ${{ matrix.config.image_name }}
  #     image_version: ${{ matrix.config.image_version }}
  #     runs_on: ubuntu-24.04-arm