name: Build Multi-Architecture ROS Containers

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # This will trigger on any tag starting with 'v', like v1.0.0
  pull_request:
    branches: [ main, master ]

jobs:
  # Detect file changes
  changes:
    runs-on: ubuntu-latest
    outputs:
      ros2-amd64: ${{ steps.filter.outputs.ros2-amd64 }}
      ros2-jetson: ${{ steps.filter.outputs.ros2-jetson }}
      workflow: ${{ steps.filter.outputs.workflow }}
      any_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history to compare with previous commits
      
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ros2-amd64:
              - 'ROS2/AMD64x86/**'
            ros2-jetson:
              - 'ROS2/Jetson/**'
            workflow:
              - '.github/workflows/**'
            any_changed:
              - 'ROS2/**'
              - '.github/workflows/**'

  # Stage 1: ROS2 base humble images (AMD64/x86)
  ros2-humble-base-amd64:
    needs: changes
    if: ${{ needs.changes.outputs.ros2-amd64 == 'true' || needs.changes.outputs.workflow == 'true' }}
    name: ROS2 Humble Base Images (AMD64)
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/AMD64x86/humble', image_name: 'humble', image_version: 'latest' }
          - { build_context: './ROS2/AMD64x86/humble_gpu', image_name: 'humble_gpu', image_version: 'latest' }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-latest

  # Stage 1: ROS2 base humble images (Jetson/ARM)
  ros2-humble-jetson:
    needs: changes
    if: ${{ needs.changes.outputs.ros2-jetson == 'true' || needs.changes.outputs.workflow == 'true' }}
    name: ROS2 Humble Jetson Base
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/Jetson/humble_jetson', image_name: 'humble_jetson', image_version: 'latest' }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-24.04-arm

  # Stage 2: ROS2 humble_harmonic (depends on base humble)
  ros2-humble-harmonic:
    needs: [changes, ros2-humble-base-amd64]
    if: ${{ needs.changes.outputs.ros2-amd64 == 'true' || needs.changes.outputs.workflow == 'true' }}
    name: ROS2 Humble Harmonic
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/AMD64x86/humble_harmonic', image_name: 'humble_harmonic', image_version: 'latest' }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-latest

  # Stage 3: ROS2 wheelchair2_base images (AMD64/x86)
  ros2-wheelchair-base:
    needs: [changes, ros2-humble-base-amd64, ros2-humble-harmonic]
    if: ${{ needs.changes.outputs.ros2-amd64 == 'true' || needs.changes.outputs.workflow == 'true' }}
    name: ROS2 Wheelchair2 Base Images
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/AMD64x86/wheelchair2_base', image_name: 'wheelchair2_base', image_version: 'latest' }
          - { build_context: './ROS2/AMD64x86/wheelchair2_base_gazebo', image_name: 'wheelchair2_base_gazebo', image_version: 'latest' }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-latest

  # Stage 3: ROS2 wheelchair2_base_jetson (depends on humble_jetson)
  ros2-wheelchair-jetson:
    needs: [changes, ros2-humble-jetson]
    if: ${{ needs.changes.outputs.ros2-jetson == 'true' || needs.changes.outputs.workflow == 'true' }}
    name: ROS2 Wheelchair2 Jetson Images
    strategy:
      matrix:
        config:
          - { build_context: './ROS2/Jetson/wheelchair2_base_jetson', image_name: 'wheelchair2_base_jetson', image_version: 'latest' }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-24.04-arm